### ISSUE TITLE
Module name override

### ISSUE THREAD

**Issue by mhuebert** [jgrodziski/metav#1]
Thanks for this project! I am interested in using it to publish a ClojureScript lib to clojars. In my case I have a dedicated repo (say, `my-lib`) which should be published to Clojars under a namespace, eg. `my-org/my-lib`. In the readme I saw a mention of an override for the module name, which might allow me to do this:

> Module's name is by default deduced from the repo path layout (but can also be overriden)

However I didn't see any other mention of this override in the readme or in my (brief) look at the source. I was wondering if I was missing something, or if you have any suggestions as to how to accomplish this. Thanks!

**Comment by jgrodziski** [comment]
Hi Matt,
You're right, the module-name override is pending...my bad. 
I was just waiting for this issue to pop-up :) I should take some time this weekend to implement it.
For consistency, the `--module-name` CLI option override should be present for the three tasks (artifact-name, spit and release).

**Comment by jgrodziski** [comment]
Hi Matt,
I've pushed the module name override feature in a dedicated branch, the test suite ran successfully but I didn't have time to test it thoroughly through the CLI.
You can test it on your side with the commit "cb493428ffe23de0a7f6e76511ba718a7217e1a2".
The new CLI option for all three tasks is:
"-r" "--module-name-override MODULE-NAME"

**Comment by mhuebert** [comment]
Thanks @jgrodziski! I tried it locally and it appears to work correctly for me.

**Comment by jgrodziski** [comment]
the module-name override feature was added in version 1.2.0.
README updated accordingly
